### ISSUE TITLE
hint.read/write((char *)(&search), sizeof(search)) is wrong!

### ISSUE THREAD

**Issue by chnmagnus** [Leviathan1995/Biu#1]
```
struct bitcask_index{
    string key;
    string file_id;
    ...
}
```
There are std::string type in the struct. So when you write the struct to file in binary. You just write the char * pointer's address to file instead of the content of the string.

**Comment by Leviathan1995** [comment]
参考 #2

**Comment by Leviathan1995** [comment]
fix
